DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_title VARCHAR(255) NOT NULL,
  map_description VARCHAR(500) NOT NULL,
  map_url VARCHAR(255) NOT NULL
);
