
DROP TABLE IF EXISTS pin_favourites CASCADE;
CREATE TABLE pin_favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  pin_id INTEGER REFERENCES pins(id) ON DELETE CASCADE

);
